apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:6st+iEPU79+JwhgdKrMOEHEra+2NKzQCgmPUn/qItU+WpGcwvE5yLw==,iv:CU1Zp0JfNPnUnY6mAtR1pOUBfna/VFvXWEAcZ/hcFZo=,tag:2/OJiHQzmIeygWQ0CdRUSw==,type:str]
sops:
  age:
    - recipient: age1dns8m4t5ee6hkxr4cuun7nj2hy0urjqnwyrhztc6qujcx7zq94dsyv5vpu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aTdkeXczb2g1ZmlXdXBZ
        RDlLc1pBM2xKNFduTkl2OTlDODRVK0tVZlg0CjduUmNWbE5jcHFtdjNlUlJLa0Fo
        SC9NVDcyRmpBTGQ2enMzM2tYT1R1bzQKLS0tIGU0czVnSnphY3N4bW9qQ1lyYUZ6
        aUw0U08vL0xwdERtT3NpRTVveGsrQlEKjs0oyeOJyluqeGhG4PsoE3rjEUiCe1b2
        VZew0mGm4DvOggLPnbiUzuTRCLga6gfjd/g9HSqfXGKffVRfGnt0oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T07:02:38Z"
  mac: ENC[AES256_GCM,data:z/iA3fBJkraH7uXvq+xm8LzZs+0aMeKaxbFBd9KJNY4mepjlu8GKNjw3hBMsdKwUfV0Bh1GWqNkxEhlqhErjg1dLdsTfgETz70egBrK5xxxYXQhHQLdA/dy7TXAHAYsvtvzOcUIG+h57mSn39hyGRVPd/Nee1TOIvbnxiVZSuTQ=,iv:Z5LnEW5qvXoqJ1IwAZgtgd8I9VdibEtH2+Nzvp+zLt8=,tag:+KTic3tM3PGzLl4Oywvcaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
