apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+E+q6IOtVrEzF7I=,iv:kGd/ZqtGMCv8DGhRhGXh5ZzvYPr4O3Z6ZVhGgo6LbJE=,tag:onFWXyfQHmLvS7uNTzqD+w==,type:str]
sops:
  age:
    - recipient: age1dns8m4t5ee6hkxr4cuun7nj2hy0urjqnwyrhztc6qujcx7zq94dsyv5vpu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZlJneWVROTk5b04yNGVh
        aXo0OTFIS05wUSttU1pML2xHSDdhU01uY2lRCi9nT1ZjYm56OUEzdllYV084WmdH
        emZGWnluTGluaHN3cGhWSEhsU0I1YkUKLS0tIFZ2T0xPdGtZWFRSWmpTeC9td0JB
        cDVRMEh6UWxBRVNSQ0J1ZUMvOHJHamsKF1K3dGccyOxMCOGbfXu99A10gUrIdAoz
        LtDym8LuByQFlOIHCVtTfIneAhWXNMDWrvD9oaYLbDptpY2jykMPLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T07:02:38Z"
  mac: ENC[AES256_GCM,data:KE+TfajyrICZycOJfiW/4WLgBxvgeEQpfWdlw778H6TfSJSbaag+8B+kgHrgLQpHoOa9CGYUpT1E9Irp3J3iGSMEdAR96jk6PoCzXsn0PSl+6BK1IM8kyQYS5vBnMSHahyWRx9qjPt00i4jc35cwirL3wZPrgSFK8CiETmYPFBA=,iv:pyzhchCT2tsgwgY/dPjSRqsNZmsV4BWuUXC3fqrapQk=,tag:SJknpamDLGPRFj8ObuhwLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
