apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:SPwtcz+UpGax831rLWXyt+QL6Xz3DNY6n04eKiT3zSw=,iv:7IO7Y/8hUMgFaAkp8GWLtqhT7X2sQZmNofgshU+UuKk=,tag:g/tcZrQjkVICMFxU+DXCBA==,type:str]
sops:
  age:
    - recipient: age1dns8m4t5ee6hkxr4cuun7nj2hy0urjqnwyrhztc6qujcx7zq94dsyv5vpu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYU4yYXhPaVJocFlkaFp5
        M2pwdjB6QUY1QVZlV1gyamlIQldVYk1aakZvCmJEK0UrRFVUWVdiMERFdXlzSU9P
        eG5KTE9HV2ZQOHFKd0FUM2VCa1cxc3MKLS0tIDVzUGIrVDhmY1VsaTZYMUdKVCtL
        RGlKOGlOZUVXdDU4MnY5YjRWTjJrZWsKsVuwF7v4Hy1oSgba00m0/caGVYfNTHQi
        s5sfeqrlmnrzFzMlo6w6VELJCjFlQaDtho50va8FFrOLKHDKXw6hGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T07:02:38Z"
  mac: ENC[AES256_GCM,data:pPZibuT7hkyqp6HYkPnMXBh9Y2D+iUFJ+gT6BUZzh6QHNpEzlLO2P8WEAqz6ZPksX7OEqIGARGz4LubIYyhqVVRSaVKgY7Mh3/g4RDmbJDDO6yM1UaIra0FcT9gymtA9Vomw0iJxRJb93Df19TXzs8YIr5c8QpuIiLt+jCQeoIE=,iv:tXBpWD+OEul3N73lrZLBkwWL+KtPiiwAfbDnFpsWQHY=,tag:Xt/HD9h4HlhBNWUW6iDhQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
