apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:RqK/6Cf7YiGfqj7c9h4WejOAjv8rfpNob9Xx51el0kYqZ9MZ9RHDYPJ48uWv/jpJ1V96gamvldCYmOqDSbu1GVWArzw2Ewcwo5sktDX+fQpyJDz0LYKRhMGA/6OVJGm2xlgv3jHH9Tess+R9SlHWNwQoFM6/II97+eC/D3ruGJgOzCq9pdm1g00h6oegliIvw+EDHwmWGNxviuqaKIa85wLzyRIh0P9riwdpXJXiwc7tEN7y,iv:g+vNtpzV0/XvVcy8wluHmfN44s90sn5ezKDhz9+jh1I=,tag:LC4bw+w01zQgaMGcNfVC+g==,type:str]
sops:
  age:
    - recipient: age1dns8m4t5ee6hkxr4cuun7nj2hy0urjqnwyrhztc6qujcx7zq94dsyv5vpu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL1FpWGhnQmp3Wi9RYnJ5
        VFoxM1pENWFNYnhPZVNHTTBWMDFiMitEZFNZCnRhVFdUajYxWVpkQVhMa0htY1BF
        K3VSL3hGS0x5SkkxaUJ4cEEyYzFpcWcKLS0tIEVsRWxvZlU4cWNTQU9WWmV6WFMz
        eGFWRGpMSENvQ3FwOEowZ2s4WjBaSEUKxYn7QHmDodYrs5aBitYduIcDko6uvB29
        mj52H1UG0txoBXlGNyvUmqewM5ro5y4eaB93rwWjja1K7CQeVj0RLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T07:02:38Z"
  mac: ENC[AES256_GCM,data:bWFe5Uxp6AJ+tJN/ir39iDRkf50re4Mp2y3X9AgSsP6KbD7PGvM4qujl+cTbEw76D/btxscWbYYFOUJe3ws8mksZOWS9R4nUcgONBztVdoUH0rF7YYj1Oiby8AC5bhHO6E0Dqu7R/1b18sf/N0tDMpvnFDVX5jCB79Wazxd993U=,iv:Co5yy78k63jrLAJrR+0VXKatUAoA4rv5Et3t1Fwe00M=,tag:TBTfEfdtavZTPfcm34PCaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
