apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0wMQIzW6DbiRhk8jVGtwfHap9v1MlAeJqkWjMjkiF4bDC/cOxU0mQA==,iv:vZj977TvOZsieVVqxgJyd+/Js5x090LkjhrBaZ7u2/A=,tag:z+5WrSjoqJowEhScnCVe+g==,type:str]
sops:
  age:
    - recipient: age1dns8m4t5ee6hkxr4cuun7nj2hy0urjqnwyrhztc6qujcx7zq94dsyv5vpu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbTZid01TL1UvSDl0Qm96
        V0pHUDZ4L2hYSDhMWHZnZUtWb0J6SlBNU2lNCldzemNZZVVUdkdzSFJXQ3o2T1pS
        cHFybmNaR0hEMmhkdStnUENZK3AwTGcKLS0tIG00cFZvMzEwM1IxYmRHMCtiYzBn
        bkFjY0kxNzFlNERqamdJNnNXb3A0K28KQrFNOJpWEfLtpQZwP8lDUQw8jKRoealK
        VZkMVojMmzhc7P819Is3PjtvyfCeILjEk2qFDDHiIMlOKRjgFMlSeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T07:02:38Z"
  mac: ENC[AES256_GCM,data:POKtbXBviqj28Tdu4mvl79omr8/rkWQitntlicwh2+4znsHbGPnbu8Ef787XIBJc3oz3ff8gDSeCOz6OowXgNQOgyG2kJlzyLa8lTvHtnGnOZu4oj/qqveqqITIHxBDoAwLl6AMXUjrHzXWhTlMUqxxX1orPMBpK/9SZ8gNfyXM=,iv:5+aznyR3bfCsI7SuFjwBFl2xRFYv2SYdM3Fkb3aGcqo=,tag:hHRE99tpsSHjzQcAyvegsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
